config/routes.rb
Assayer::Application.routes.draw do

  devise_for :users

  resources :assignments, :only => [:index] do
    resources :scenarios, :only => [:show] do
      get 'next', :on => :collection
      resources :items, :only => [:show, :index] do
        get 'next', :on => :collection
        resources :item_ratings, :only => [:new, :edit, :update, :create]
      end
    end
  end
  root :to => "home#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for :title, page_title.to_s
    @show_title = show_title
  end

  def show_title?; @show_title; end
end

app/views/layouts/_footer.html.haml
%small.copyright
  Copyright &copy; #{Date.today.year}

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title
  = h(yield(:title) || "Assayer")
  
%meta{ :name => "description", :content => "" }/
%meta{ :name => "author", :content => "" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/

-# Place favicon.ico and apple-touch-icon.png in the root of your domain and delete these references
-# %link{ :rel => "shortcut icon", :href => "/favicon.ico" }/
-# %link{ :rel => "apple-touch-icon", :href => "/apple-touch-icon.png" }/

-# You can specify a stylesheet_partial when rendering this partial (i.e. admin/stylesheets)
- if local_assigns[:stylesheet_partial]
  = render :partial => local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects
= javascript_include_tag 'modernizr.min'

= csrf_meta_tag

app/views/layouts/_header.html.haml
- if show_title?
  %h1=h yield(:title)
%p 
  -if current_user.present?
    Logged in as #{current_user.name}.
    = link_to "Logout", destroy_user_session_path
  -else
    = link_to_unless_current "Login", new_user_session_path do
      &nbsp;
= yield(:header)

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery, with a protocol relative URL
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
-# remote_jquery and local_jquery helpers use minified jquery unless Rails.env is development
- if !google_api_key.blank?
  = javascript_include_tag "//www.google.com/jsapi?key=#{google_api_key}"
  :javascript
    google.load(#{ remote_jquery("1.5.2") });
- else
  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/#{ local_jquery("1.5.2") }"

-# fall back to local jQuery if necessary
:javascript
  window.jQuery || document.write("<script src='/javascripts/jquery.min.js'>\x3C/script>")
  
= javascript_include_tag 'rails', 'plugins', 'application'

-# Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb
/[if lt IE 7 ]
  = javascript_include_tag 'dd_belatedpng.js'
  :javascript
    //DD_belatedPNG.fix('img, .png_bg');
    
-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[["_setAccount","#{google_account_id}"],["_trackPageview"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));

app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'style', :media => 'all'

-# Uncomment if you are specifically targeting less enabled mobile browsers
-#= stylesheet_link_tag 'handheld', :media => 'handheld'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
- ie_html(:class => 'no-js', :lang => 'en') do
  %head
    %meta{ :charset => "utf-8" }/
    %meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/
    %meta{ :name => "description", :content => "Assayer Search Test System" }/
    %meta{ :name => "author", :content => "Tarik K. Alkasab, MD, PhD" }/
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/

    %title
      = h(yield(:title) || "Assayer")

    = stylesheet_link_tag "application"
    = javascript_include_tag '/javascripts/modernizr.min.js'
    = csrf_meta_tag
  
  %body{ :class => "#{controller.controller_name}" }
    -# Top Bar
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{:data=>{:toggle => "collapse", :target => ".nav-collapse"}}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href=>"#"} Assayer
          .nav-collapse
            %ul.nav
              - navbar_link('Home', root_path)
              - navbar_link('About', about_path)
              - navbar_link('Help', help_path)
              %li.divider-vertical
              - if user_signed_in?
                %li
                  .navbar-text Logged in as #{current_user.name}
                %li
                  %a{:href => destroy_user_session_path} Sign out
              - else
                %li= link_to 'Sign In', new_session_path(:user)
                %li= link_to 'Sign Up', new_registration_path(:user)

    -# Main Content
    .container
      -# Flash messages
      - flash.each do |name, msg|
        .alert{ :class => name == :notice ? 'alert-success' : 'alert-error' }
          %a.close{:data => {:dismiss => 'alert'}} &times;
          = msg

      -# Main content
      = yield
        
    -# Javascript
    = javascript_include_tag "application"